### PR TITLE
Prevent double punctuation

### PR DESCRIPTION
**Pull request by ZeldaZach**
@poixen doesn't want users to be able to reg a name like "bing.......o" so this prevents the use of two dots/periods, along with any punctuation mark, in a row anywhere in a username.

This also prevents people from starting a username with something other than a letter (A-Z, a-z) or a number (0-9)

Valid:
+ **Bing.o_man3**
+ **Chinese_food_**
+ **8Radish-b_tree.**

Invalid:
+ **The_cheesey_one-_-**
    + The -_ is invalid as it's two punc in a row
+ **Red_cross..30**
    + The .. is invalid as it's two punc in a row
+ **_I.Love.Bacon.**
    + The _ is invalid because you can only start with a letter / number

### CODE REVIEW

**Comment by poixen** [comment]
Shame some users already have [punctuation]name :/

**Comment by Daenyth** [comment]
Why should we block leading punctuation? 

What is the point of these restrictions? It seems incredibly arbitrary. Allowing only ascii makes sense from a security perspective because of unicode lookalike names. Length limits make sense for UI assumptions. But this seems pointless

**Comment by ZeldaZach** [comment]
Talk to @poixen, I'm just doing what he requested. I don't have a preference on this issue.

**Comment by poixen** [comment]
I want to prevent usernames like 
"......----___--.-.-.-.-.-___--..-" <-- should be valid right now
Its a mess and is not a username.

**Comment by ZeldaZach** [comment]
I only built it for periods not  other symbols...

**Comment by Daenyth** [comment]
Maybe we can block repeating punctuation but allow leading punctuation?

**Comment by poixen** [comment]
I think punctuation should connect words. You should not be allowed to have 2 punctuation marks next to one another. As for leading punctuation, I think it looks messy, though not as bad as double + marks next to one another.

**Comment by ZeldaZach** [comment]
So you want double punctuation of any kind blocked? I.e. "me_.p" is not allowed

Thanks,
Zachary Halpern
www.ZachHalpern.com

**Comment by poixen** [comment]
I would like that yes. Again, where else is this kind of username allowed?

**Comment by ZeldaZach** [comment]
@poixen I'll do as you request

**Comment by ZeldaZach** [comment]
I added some examples in the PR

**Comment by ZeldaZach** [comment]
Updated to include new rules in registration file

**Comment by poixen** [comment]
This good to go?

**Pull request closed without merging**
